mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  global-config:
    db-column-underline: false
  mapper-locations: classpath:/mapping/*.xml

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: my-secret-pw
    url: jdbc:mysql://localhost:3306/heimdallr_db
    username: root
