mybatis-plus:
  configuration:
#  this config used to print sql in local to see the sql
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: false
  global-config:
    db-column-underline: false
  mapper-locations: classpath:/mapping/*.xml
  type-handlers-package: org.iman.Heimdallr.config.handler

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: my-secret-pw
    url: jdbc:mysql://localhost:3306/heimdallr_db
    username: root
